// ============================================================
// InstaRatiba — Segment 9
// src/lib/supabase/dashboard.ts
// Data layer for dashboard: timetable listing, versioning,
// duty roster, auto-generate duty assignments.
// §5.1 Dashboard  |  §5.5 Versioning  |  §5.7 Duty Roster
// ============================================================

import { supabase }  from './client'
import type { Timetable, Teacher } from '@/types'

// ── Timetable listing ─────────────────────────────────────────

export async function fetchTimetables(schoolId: string): Promise<Timetable[]> {
  const { data, error } = await supabase
    .from('timetables')
    .select('*')
    .eq('school_id', schoolId)
    .order('created_at', { ascending: false })

  if (error) throw new Error(error.message)
  return (data ?? []) as Timetable[]
}

// ── Create timetable ─────────────────────────────────────────

export async function createTimetable(
  tt: Pick<Timetable, 'school_id' | 'term_id' | 'name' | 'status'>
): Promise<Timetable> {
  const { data, error } = await supabase
    .from('timetables')
    .insert({
      id:         crypto.randomUUID(),
      school_id:  tt.school_id,
      term_id:    tt.term_id,
      name:       tt.name,
      status:     tt.status,
      created_at: new Date().toISOString(),
    })
    .select()
    .single()

  if (error) throw new Error(error.message)
  return data as Timetable
}

// ── Delete timetable ─────────────────────────────────────────

export async function deleteTimetable(id: string): Promise<void> {
  // Delete dependent rows first (if no cascade in DB)
  await supabase.from('timetable_slots').delete().eq('timetable_id', id)
  await supabase.from('conflicts').delete().eq('timetable_id', id)
  await supabase.from('duty_roster').delete().eq('timetable_id', id)
  await supabase.from('timetable_share_tokens').delete().eq('timetable_id', id)
  await supabase.from('approval_comments').delete().eq('timetable_id', id)

  const { error } = await supabase.from('timetables').delete().eq('id', id)
  if (error) throw new Error(error.message)
}

// ── Duplicate timetable ───────────────────────────────────────

export async function duplicateTimetable(
  source: Timetable,
  schoolId: string,
): Promise<Timetable> {
  const newId   = crypto.randomUUID()
  const newName = `${source.name} (copy)`

  // Create new timetable row
  const { data: newTt, error } = await supabase
    .from('timetables')
    .insert({
      id:         newId,
      school_id:  schoolId,
      term_id:    source.term_id,
      name:       newName,
      status:     'draft',
      created_at: new Date().toISOString(),
    })
    .select()
    .single()

  if (error) throw new Error(error.message)

  // Copy slots
  const { data: slots } = await supabase
    .from('timetable_slots')
    .select('*')
    .eq('timetable_id', source.id)

  if (slots && slots.length > 0) {
    const newSlots = slots.map(s => ({
      ...s,
      id:           crypto.randomUUID(),
      timetable_id: newId,
    }))
    await supabase.from('timetable_slots').insert(newSlots)
  }

  return newTt as Timetable
}

// ── Duty Roster ───────────────────────────────────────────────

export interface DutyAssignment {
  id:           string
  timetable_id: string
  teacher_id:   string
  duty_type:    string   // 'assembly' | 'lunch' | 'gate'
  day:          string   // 'Monday' … 'Friday'
}

export async function fetchDutyRoster(timetableId: string): Promise<DutyAssignment[]> {
  const { data, error } = await supabase
    .from('duty_roster')
    .select('*')
    .eq('timetable_id', timetableId)

  if (error) throw new Error(error.message)
  return (data ?? []) as DutyAssignment[]
}

export async function saveDutyRoster(
  timetableId: string,
  assignments: DutyAssignment[],
): Promise<void> {
  // Delete existing and re-insert (upsert by composite key is simpler this way)
  await supabase.from('duty_roster').delete().eq('timetable_id', timetableId)

  if (assignments.length === 0) return

  const rows = assignments.map(a => ({
    id:           a.id || crypto.randomUUID(),
    timetable_id: timetableId,
    teacher_id:   a.teacher_id,
    duty_type:    a.duty_type,
    day:          a.day,
  }))

  const { error } = await supabase.from('duty_roster').insert(rows)
  if (error) throw new Error(error.message)
}

// ── Auto-generate duty roster ─────────────────────────────────

const DAYS   = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
const DUTIES = ['assembly', 'lunch', 'gate']

/**
 * Auto-assigns teachers to duty slots by rotating through the teacher list.
 * A production version would fetch free-period data from timetable_slots,
 * but for the MVP we round-robin across available teachers.
 */
export async function autoGenerateDutyRoster(
  timetableId: string,
  teachers:    Teacher[],
): Promise<DutyAssignment[]> {
  if (teachers.length === 0) throw new Error('No teachers available')

  const assignments: DutyAssignment[] = []
  let idx = 0

  for (const day of DAYS) {
    for (const duty of DUTIES) {
      // Try to find a teacher not already on duty today
      const todayAssigned = assignments
        .filter(a => a.day === day)
        .map(a => a.teacher_id)

      let chosen = teachers.find(t => !todayAssigned.includes(t.id))
      if (!chosen) {
        // All teachers used today — fall back to round-robin
        chosen = teachers[idx % teachers.length]
      }
      idx++

      assignments.push({
        id:           crypto.randomUUID(),
        timetable_id: timetableId,
        teacher_id:   chosen.id,
        duty_type:    duty,
        day,
      })
    }
  }

  return assignments
}
