// ============================================================
// InstaRatiba — src/lib/supabase/index.ts
// ============================================================

export { supabase } from './client'
export * from './school'
export { fetchClasses, upsertClass, deleteClass } from './classes'
export * from './rooms'
export * from './teachers'
export * from './allocations'

// Timetable — exclude share tokens (canonical in settings.ts)
export {
  fetchTimetables,
  fetchTimetableById,
  createTimetable,
  updateTimetableStatus,
  deleteTimetable,
  fetchSlots,
  bulkInsertSlots,
  clearSlots,
  updateSlot,
  saveConflicts,
  fetchConflicts,
  resolveConflict,
  saveOverride,
  fetchOverrides,
} from './timetable'

export * from './approvalComments'

// Dashboard — exclude fns duplicated from timetable.ts
export {
  duplicateTimetable,
  fetchDutyRoster,
  saveDutyRoster,
  autoGenerateDutyRoster,
} from './dashboard'

// Settings — canonical for share tokens & school update
export * from './settings'
