// ============================================================
// InstaRatiba — Segment 9
// DutyRosterPanel.tsx
// Auto-generates duty roster from teacher free periods.
// §5.7 Duty Roster Generation
// ============================================================

import { useEffect, useState, useCallback } from 'react'
import { toast } from 'sonner'
import { SkeletonLoader } from '@/components/ui'
import type { Teacher } from '@/types'
import {
  fetchDutyRoster, saveDutyRoster, autoGenerateDutyRoster,
  type DutyAssignment,
} from '@/lib/supabase/dashboard'

const DAYS   = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
const DUTIES = [
  { key: 'assembly',  label: 'Morning Assembly', icon: 'bi-sunrise',      color: '#1565C0' },
  { key: 'lunch',     label: 'Lunch Supervision', icon: 'bi-cup-hot',     color: '#E65100' },
  { key: 'gate',      label: 'Gate Duty',          icon: 'bi-door-open',  color: '#2E7D32' },
]

interface Props {
  timetableId: string | undefined
  teachers:    Teacher[]
}

export default function DutyRosterPanel({ timetableId, teachers }: Props) {
  const [assignments, setAssignments]   = useState<DutyAssignment[]>([])
  const [isLoading, setIsLoading]       = useState(false)
  const [isSaving, setIsSaving]         = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)

  const load = useCallback(async () => {
    if (!timetableId) return
    setIsLoading(true)
    try {
      const data = await fetchDutyRoster(timetableId)
      setAssignments(data)
    } catch {
      // Empty — not yet generated
    } finally {
      setIsLoading(false)
    }
  }, [timetableId])

  useEffect(() => { load() }, [load])

  // ── Auto-generate ──────────────────────────────────────────
  const handleAutoGenerate = async () => {
    if (!timetableId) { toast.error('No active timetable'); return }
    if (teachers.length === 0) { toast.error('No teachers loaded'); return }
    setIsGenerating(true)
    try {
      const generated = await autoGenerateDutyRoster(timetableId, teachers)
      setAssignments(generated)
      toast.success('Duty roster auto-generated')
    } catch (e) {
      toast.error('Auto-generate failed: ' + (e as Error).message)
    } finally {
      setIsGenerating(false)
    }
  }

  // ── Manual change ──────────────────────────────────────────
  const handleChange = (day: string, dutyKey: string, teacherId: string) => {
    setAssignments(prev => {
      const existing = prev.find(a => a.day === day && a.duty_type === dutyKey)
      if (existing) {
        return prev.map(a =>
          a.day === day && a.duty_type === dutyKey ? { ...a, teacher_id: teacherId } : a
        )
      }
      return [...prev, {
        id:           crypto.randomUUID(),
        timetable_id: timetableId ?? '',
        teacher_id:   teacherId,
        duty_type:    dutyKey,
        day,
      }]
    })
  }

  // ── Save ───────────────────────────────────────────────────
  const handleSave = async () => {
    if (!timetableId) return
    setIsSaving(true)
    try {
      await saveDutyRoster(timetableId, assignments)
      toast.success('Duty roster saved')
    } catch (e) {
      toast.error('Save failed: ' + (e as Error).message)
    } finally {
      setIsSaving(false)
    }
  }

  const getTeacher = (day: string, duty: string) =>
    assignments.find(a => a.day === day && a.duty_type === duty)?.teacher_id ?? ''

  if (isLoading) return <SkeletonLoader lines={6} />

  return (
    <div className="space-y-4">

      {/* Toolbar */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        <p className="text-sm text-[--color-muted]">
          Assign teachers to supervision duties. Free-period teachers are automatically matched.
        </p>
        <div className="flex gap-2 flex-wrap">
          <button
            onClick={handleAutoGenerate}
            disabled={isGenerating || !timetableId}
            className="text-sm border border-[--color-accent-light] text-[--color-primary] rounded-xl px-4 py-2 hover:bg-green-50 transition-colors disabled:opacity-60"
          >
            {isGenerating
              ? <><i className="bi bi-arrow-repeat animate-spin mr-1.5" />Generating…</>
              : <><i className="bi bi-magic mr-1.5" />Auto-Generate</>
            }
          </button>
          {assignments.length > 0 && (
            <>
              <button
                onClick={() => { /* duty roster PDF export — TODO: implement */ }}
                className="text-sm border border-[--color-accent-light] text-[--color-muted] rounded-xl px-4 py-2 hover:border-[--color-primary] hover:text-[--color-primary] transition-colors"
              >
                <i className="bi bi-file-earmark-pdf mr-1.5" />Export PDF
              </button>
              <button
                onClick={handleSave}
                disabled={isSaving}
                className="text-sm bg-[--color-primary] text-white rounded-xl px-4 py-2 hover:bg-[--color-mid] transition-colors disabled:opacity-60"
              >
                {isSaving ? <i className="bi bi-arrow-repeat animate-spin mr-1.5" /> : null}
                Save Roster
              </button>
            </>
          )}
        </div>
      </div>

      {/* Roster grid */}
      {teachers.length === 0 ? (
        <div className="bg-[--color-surface] rounded-2xl p-8 text-center">
          <i className="bi bi-people text-3xl text-[--color-accent-light] block mb-2" />
          <p className="text-sm text-[--color-muted]">No teachers loaded. Go to Teacher Manager first.</p>
        </div>
      ) : (
        <div className="overflow-x-auto rounded-2xl border border-[--color-accent-light]">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-[--color-surface]">
                <th className="text-left px-4 py-3 text-xs font-semibold text-[--color-muted] uppercase tracking-wider w-40">
                  Duty
                </th>
                {DAYS.map(d => (
                  <th key={d} className="px-3 py-3 text-xs font-semibold text-[--color-muted] uppercase tracking-wider text-center">
                    {d.slice(0, 3)}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {DUTIES.map((duty, di) => (
                <tr key={duty.key} className={di % 2 === 0 ? 'bg-white' : 'bg-[--color-surface]'}>
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-2">
                      <i className={`${duty.icon} text-base`} style={{ color: duty.color }} />
                      <span className="font-medium text-[--color-text] text-xs">{duty.label}</span>
                    </div>
                  </td>
                  {DAYS.map(day => (
                    <td key={day} className="px-2 py-2 text-center">
                      <select
                        value={getTeacher(day, duty.key)}
                        onChange={e => handleChange(day, duty.key, e.target.value)}
                        className="text-xs border border-[--color-accent-light] rounded-lg px-2 py-1.5 bg-white focus:outline-none focus:ring-1 focus:ring-[--color-primary] w-full max-w-[120px]"
                      >
                        <option value="">— none —</option>
                        {teachers.map(t => (
                          <option key={t.id} value={t.id}>{t.name}</option>
                        ))}
                      </select>
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}
